// ── Données centralisées du portfolio ────────────────────────
// Modifier ce fichier pour mettre à jour toutes les pages.
//
// Vidéos multiples : utiliser "videos: [url1, url2, ...]"
// Vidéo unique     : utiliser "video: url"  (rétrocompatible)

window.PROJECTS = [
  {
    title: "Autoportrait",
    type: "Papier & Crayon",
    tag: "Gobelins", color: "blue",
    year: 2022, month: 8, date: "SEPT. 2022",
    img: "/realisation/Autoportart.jpg",
    desc: "Réalisation d'un autoportrait où je devais me représenter par ce que j'aime",
    duration: "1 semaine",
    role: ["Dessinateur", "Concepteur de l'image", "Choix des éléments visuels"],
    learned: ["Croquis", "dessin", "composition visuelle"],
    tools: [],
    link: "#"
  },
  {
    title: "Montre vectorisée",
    type: "Illustrator",
    tag: "Gobelins", color: "blue",
    year: 2022, month: 9, date: "OCT. 2022",
    img: "/realisation/montre/montre-realise.png",
    gallery: ["/realisation/montre/montre-realise.png", "/realisation/montre/montre-de-base.png"],
    desc: "Vectorisation d'une montre à partir d'une image de référence",
    duration: "3 semaines",
    role: ["Vectoriseur"],
    learned: ["Illustrator"],
    tools: ["Il"],
    link: "#"
  },
  {
    title: "Vinyle",
    type: "Illustrator & Photoshop",
    tag: "Gobelins", color: "blue",
    year: 2022, month: 10, date: "NOV. 2022",
    img: "/realisation/vinyle/Recto.png",
    gallery: ["/realisation/vinyle/Recto.png", "/realisation/vinyle/macarron.png", "/realisation/vinyle/Verso.png", "/realisation/vinyle/macarron-2.png"],
    desc: "Création d'un visuel de pochette de vinyle, avec recto et verso, avec les macarons",
    duration: "2 semaines",
    role: ["Illustrateur", "Imprimeur"],
    learned: ["Mise en page pour impression", "Photoshop", "Illustrator", "InDesign"],
    tools: ["Il", "Ps", "Id"],
    link: "#"
  },
  {
    title: "Carte de visite",
    type: "InDesign",
    tag: "Gobelins", color: "blue",
    year: 2023, month: 0, date: "JAV. 2023",
    img: "/realisation/cartedevisite/logo.png",
    gallery: ["/realisation/cartedevisite/logo.png", "/realisation/cartedevisite/texte.png"],
    desc: "Création d'une carte de visite professionnelle.",
    duration: "1 Mois",
    role: ["Designer", "Mise en page", "Création de logo"],
    learned: ["InDesign", "typographie", "composition visuelle"],
    tools: ["Id"],
    link: "#"
  },
  {
    title: "Revolte",
    type: "Jeu De Carte",
    tag: "Gobelins", color: "blue",
    year: 2023, month: 1, date: "FEV. 2023",
    img: "/realisation/carte/dos.png",
    gallery: ["/realisation/carte/dos.png", "/realisation/carte/blanc/onjn.png", "/realisation/carte/blanc/revolution.png", "/realisation/carte/jeuechec.png"],
    desc: "Un jeu de carte sur les visuels des échecs et sur les règles du jeu Exploding Kittens",
    duration: "2 Mois",
    role: ["Game Designer & Level Designer", "Illustrateur", "Équilibrage", "Imprimeur", "Testeur"],
    learned: ["Concevoir des niveaux immersifs et cohérents", "Travailler en équipe avec une bonne organisation", "Itérer grâce aux tests joueurs"],
    tools: ["Id", "Il"],
    link: "#"
  },
  {
    title: "Decoration",
    type: "Decoupeuse laser",
    tag: "Personnel", color: "pink",
    year: 2023, month: 4, date: "MAI 2023",
    img: "/realisation/decoration.png",
    desc: "Création d'une décoration en bois avec gravure à la découpeuse laser",
    duration: "1 semaine",
    role: ["Designer"],
    learned: ["Découpeuse laser", "Illustrator"],
    tools: ["Il"],
    link: "#"
  },
  {
    title: "Around The Rock",
    type: "création d'identité visuelle",
    tag: "Gobelins", color: "blue",
    year: 2023, month: 5, date: "JUIN 2023",
    img: "/realisation/festival/mindmapping.png",
    gallery: [
      "/realisation/festival/mindmapping.png",
      "/realisation/festival/billetfestival.png",
      "/realisation/festival/lisseappli.png",
      "/realisation/festival/lissesite.png",
      "/realisation/festival/Plan-de-travail1.png",
      "/realisation/festival/Plan.png",
      "/realisation/festival/Plandetravail.png"
    ],
    desc: "Création d'un festival de musique avec une identité visuelle cohérente",
    duration: "2 mois",
    role: ["Designer", "Créateur d'identité visuelle", "Concepteur de l'expérience globale"],
    learned: ["Travail d'équipe", "gestion de projet", "création d'une identité visuelle"],
    tools: ["Id", "Ps", "Il"],
    link: "#"
  },
  {
    title: "Photographie",
    type: "Photographie",
    tag: "Gobelins", color: "blue",
    year: 2023, month: 9, date: "OCT. 2023",
    img: "/realisation/Autoportart.jpg",
    desc: "Prototype atmosphérique basé sur le froid, le silence et la progression lente.",
    duration: "1 Semaine",
    role: ["Direction d'ambiance", "Level Design", "Prototype d'exploration"],
    learned: ["Créer une ambiance forte avec peu d'éléments", "Travailler le silence et le rythme", "Construire une progression lente"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Enfain",
    type: "Application",
    tag: "Gobelins", color: "blue",
    year: 2023, month: 11, date: "DEC. 2023",
    img: "/realisation/Autoportart.jpg",
    desc: "Prototype atmosphérique basé sur le froid, le silence et la progression lente.",
    duration: "1 Mois",
    role: ["Direction d'ambiance", "Level Design", "Prototype d'exploration"],
    learned: ["Créer une ambiance forte avec peu d'éléments", "Travailler le silence et le rythme", "Construire une progression lente"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Whellcome To Hell",
    type: "Vidéo IA",
    tag: "Gobelins", color: "blue",
    year: 2024, month: 2, date: "MARS. 2024",
    img: "/realisation/vinyle/macarron-2.png",
    video: "https://www.youtube.com/embed/mYO2WOaA8CU?si=jT7o28wQXJ149gHN",
    desc: "Nouvelle version du projet cyberpunk avec meilleure lisibilité des parcours.",
    duration: "1 Semaine",
    role: ["Level Designer", "Refonte des parcours", "Optimisation de la lisibilité"],
    learned: ["Améliorer un niveau existant", "Hiérarchiser les repères visuels", "Rendre un parcours plus fluide"],
    tools: ["U", "VS", "Ps"],
    link: "#"
  },
  {
    title: "Animation 3D",
    type: "Vidéo",
    tag: "Gobelins", color: "blue",
    year: 2024, month: 3, date: "AVR. 2024",
    img: "/realisation/Pokeball.png",
    video: "https://www.youtube.com/embed/sAeUvNG19OA?si=KS0gEqwmWWne0eha",
    desc: "Nouvelle version du projet cyberpunk avec meilleure lisibilité des parcours.",
    duration: "1 Semaine",
    role: ["Level Designer", "Refonte des parcours", "Optimisation de la lisibilité"],
    learned: ["Améliorer un niveau existant", "Hiérarchiser les repères visuels", "Rendre un parcours plus fluide"],
    tools: ["U", "VS", "Ps"],
    link: "#"
  },
  {
    title: "Course de la mort",
    type: "Jeux vidéo",
    tag: "Gobelins", color: "blue",
    year: 2024, month: 4, date: "MAI 2024",
    img: "/realisation/Autoportart.jpg",
    desc: "Prototype atmosphérique basé sur le froid, le silence et la progression lente.",
    duration: "1 Semaine",
    role: ["Direction d'ambiance", "Level Design", "Prototype d'exploration"],
    learned: ["Créer une ambiance forte avec peu d'éléments", "Travailler le silence et le rythme", "Construire une progression lente"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    id: "floatland",
    title: "FloatLand",
    type: "Jeux vidéo VR",
    platform: "VR / PC",
    tag: "Gobelins", color: "blue",
    year: 2024, month: 5, date: "JUIN. 2024",
    team: "3 personnes",
    engine: "Unity",
    img: "/realisation/floatland/floatland.png",
    video: "https://www.youtube.com/embed/mYO2WOaA8CU?si=jT7o28wQXJ149gHN",
    desc: "Jeux de relaxation",
    duration: "Projet fin d'année",
    role: ["Game Designer", "Level Designer", "Développeur"],
    contributions: ["Conception du level design", "Mécaniques de gameplay", "Développement Unity"],
    learned: ["Améliorer un niveau existant", "Hiérarchiser les repères visuels", "Rendre un parcours plus fluide"],
    tools: ["U", "VS", "Ps"],
    link: "#"
  },
  {
    id: "infinitydot",
    title: "Infinity Dot",
    type: "Site Three.js",
    platform: "Web",
    tag: "Gobelins", color: "blue",
    year: 2024, month: 9, date: "OCT. 2024",
    team: "Solo",
    engine: "Three.js",
    img: "/realisation/infinitydot.png",
    desc: "Representé la fin de toute chose",
    duration: "1 semaine",
    role: ["Développeur", "Designer"],
    contributions: ["Création de la scène Three.js", "Animation des particules", "Design et intégration"],
    learned: ["Améliorer un ancien concept", "Rendre une DA plus cohérente", "Clarifier l'expérience joueur"],
    tools: ["U", "Bl", "Ps"],
    link: "/pages/infinitydot.html"
  },
  {
    id: "dotmusic",
    title: "Dot Music",
    type: "Site Vue.js",
    platform: "Web",
    tag: "Gobelins", color: "blue",
    year: 2024, month: 10, date: "NOV. 2024",
    team: "Solo",
    engine: "Vue.js",
    img: "/realisation/dotmusic.png",
    desc: "Representé le son de manière visuel",
    duration: "1 semaine",
    role: ["Développeur", "Designer"],
    contributions: ["Visualisation audio réactive", "Lien entre son et animation", "Interface interactive"],
    learned: ["Améliorer un ancien concept", "Rendre une DA plus cohérente", "Clarifier l'expérience joueur"],
    tools: ["U", "Bl", "Ps"],
    link: "/pages/dotmusic.html"
  },
  {
    title: "Mac's Story",
    type: "Vidéo",
    tag: "Gobelins", color: "blue",
    year: 2024, month: 11, date: "DEC. 2024",
    img: "/realisation/vinyle/macarron.png",
    video: "https://www.youtube.com/embed/jl-DCLoXv2w?si=Si-nQJpyGj4MTeXj",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "2 semaines",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Memoir Level Design",
    type: "Memoir",
    tag: "Gobelins", color: "blue",
    year: 2025, month: 1, date: "JAV. 2025",
    img: "/realisation/memoir/abstract.png",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "6 Mois",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Fragment",
    type: "Jeux vidéo",
    tag: "Gobelins", color: "blue",
    year: 2025, month: 5, date: "JUIN 2025",
    img: "/realisation/fragment/fragment.png",
    video: "https://www.youtube.com/watch?v=p1svvKTsktk",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "6 Mois",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Game Designer - So'Briquet",
    type: "Jeux vidéo",
    tag: "IIM", color: "orange",
    year: 2025, month: 8, date: "SEPT. 2025",
    img: "/realisation/sobriquet/sobriquet.png",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "1 Mois",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Level Design Portal 2",
    type: "Jeux vidéo",
    tag: "IIM", color: "orange",
    year: 2025, month: 9, date: "OCT. 2025",
    img: "/realisation/vinyle/macarron.png",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "1 Mois",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Modvember",
    type: "Jeux vidéo",
    tag: "Personnel", color: "pink",
    year: 2025, month: 10, date: "NOV. 2025",
    img: "/realisation/vinyle/macarron.png",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "6 Mois",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Level Design Far Cry 5",
    type: "Blocking",
    tag: "IIM", color: "orange",
    year: 2025, month: 11, date: "DEC. 2025",
    img: "/realisation/vinyle/macarron.png",
    video: "https://www.youtube.com/watch?v=O8hXSBKPLLQ",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "6 Mois",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    id: "longnigth",
    title: "Long Night At Grandma's",
    type: "Jeux vidéo",
    platform: "Mobile",
    tag: "IIM", color: "orange",
    year: 2026, month: 1, date: "FEV. 2026",
    team: "Équipe",
    engine: "Unity",
    img: "/realisation/longnigth/longnigth.png",
    desc: "Jeu de reflexion sur mobile",
    duration: "1 Mois",
    role: ["Lead Game Designer"],
    contributions: ["Direction du game design", "Conception des mécaniques", "Itération et tests"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Golf Unreal Engine",
    type: "Jeux vidéo",
    tag: "IIM", color: "orange",
    year: 2026, month: 3, date: "AVR. 2026",
    img: "/realisation/vinyle/macarron.png",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "1 Mois",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Level Design Plague Tale",
    type: "Jeux vidéo",
    tag: "IIM", color: "orange",
    year: 2026, month: 4, date: "MAI 2026",
    img: "/realisation/vinyle/macarron.png",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "1 Mois",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
  {
    title: "Project Unreal Engine",
    type: "Jeux vidéo",
    tag: "IIM", color: "orange",
    year: 2026, month: 5, date: "JUIN 2026",
    img: "/realisation/vinyle/macarron.png",
    desc: "Prototype orienté combat, feedback visuel et sensations de jeu.",
    duration: "1 Mois",
    role: ["Combat Design", "Feedback visuel", "Tests de sensations"],
    learned: ["Améliorer le ressenti des actions", "Créer des feedbacks lisibles", "Tester rapidement une mécanique"],
    tools: ["UE", "Bl", "Ps"],
    link: "#"
  },
];

window.DIPLOMAS = [
  {
    title: "Debut de formation",
    subtitle: "Coder sa créativité <br> DNMADe Mention Numerique",
    date: "Debut de formation",
    year: 2022, month: 8
  },
  {
    title: "Alternance",
    subtitle: "Alternance chez Scale",
    date: "Technicien du spectacle",
    year: 2023, month: 11
  },
  {
    title: "DIPLÔME OBTENU",
    subtitle: "Coder sa créativité",
    date: "DNMADe Mention Numerique",
    year: 2025, month: 5
  },
  {
    title: "Debut de formation",
    subtitle: "Game Design & Level Design <br> Bachelor IIM",
    date: "Debut de formation",
    year: 2025, month: 8
  },
];

window.GAMES = [
  {
    title: "Floatland",
    type: "Jeu vidéo",
    mode: "Équipe",
    year: "2024",
    platform: "VR / PC",
    engine: "Unity",
    duration: "Projet fin d'année",
    team: "3 personnes",
    role: "Level Design, Game Design, Développement Unity, Implémentation",
    tools: ["Unity", "Blender", "C#", "VR"],
    image: "/realisation/floatland/floatland.png",
    description: "Jeu VR composé d'îles thématiques, chacune avec son identité visuelle et ses mini-jeux. Le joueur explore un monde lowpoly pensé pour l'immersion et l'interaction.",
    contributions: [
      "Conception du level design des îles",
      "Création des mécaniques de mini-jeux",
      "Intégration et développement dans Unity",
      "Réflexion sur l'expérience utilisateur en VR"
    ]
  },
  {
    title: "Révolte",
    type: "Jeu de cartes",
    mode: "Solo",
    year: "2023",
    platform: "Physique",
    engine: "Prototype papier",
    duration: "Projet de cours",
    team: "Solo",
    role: "Game Design, règles, cartes, prototype interactif",
    tools: ["Photoshop", "Illustrator", "JavaScript"],
    image: "/realisation/carte/dos.png",
    description: "Jeu de société interactif pensé pour 4 joueurs, basé sur des cartes, des effets et une logique d'affrontement entre factions.",
    contributions: [
      "Création des règles de jeu",
      "Conception des cartes et de leurs effets",
      "Direction graphique du jeu",
      "Prototype interactif sur le portfolio"
    ]
  },
  {
    title: "After the Révolte",
    type: "Prototype",
    mode: "Solo",
    year: "2023",
    platform: "PandaSuite",
    engine: "PandaSuite",
    duration: "Projet court",
    team: "Solo",
    role: "Narration interactive, UX, prototypage",
    tools: ["PandaSuite", "Photoshop"],
    image: "/realisation/afterrevolt/moyen.png",
    description: "Prototype narratif inspiré de Reigns, où le joueur avance par décisions successives et conséquences immédiates.",
    contributions: [
      "Structure de l'expérience interactive",
      "Création du système de décisions",
      "Écriture des situations",
      "Intégration sur PandaSuite"
    ]
  },
  {
    title: "Infinity Dot",
    type: "Prototype",
    mode: "Solo",
    year: "2024",
    platform: "Web",
    engine: "Three.js",
    duration: "Projet court",
    team: "Solo",
    role: "Développement créatif, expérimentation visuelle",
    tools: ["Three.js", "JavaScript"],
    image: "/realisation/infinitydot.png",
    description: "Expérimentation visuelle autour de particules et de formes génératives en Three.js.",
    contributions: [
      "Création d'une scène interactive",
      "Manipulation de formes et particules",
      "Recherche esthétique autour du mouvement",
      "Développement web créatif"
    ]
  },
  {
    title: "Dot Musique",
    type: "Prototype",
    mode: "Solo",
    year: "2024",
    platform: "Web",
    engine: "Vue.js",
    duration: "Projet court",
    team: "Solo",
    role: "Développement web, interaction audio",
    tools: ["Vue.js", "JavaScript"],
    image: "/realisation/dotmusic.png",
    description: "Visualisation audio réactive qui explore l'effet du son sur des particules et éléments graphiques.",
    contributions: [
      "Création d'une interface interactive",
      "Lien entre son et animation",
      "Expérimentation avec Vue.js",
      "Travail sur le rythme visuel"
    ]
  },
  {
    title: "Fragment",
    type: "Jeu vidéo",
    mode: "Solo",
    year: "2025",
    platform: "PC",
    engine: "Unity",
    duration: "3 Mois",
    team: "Solo",
    role: "Développeur, Level Designer, Game Designer",
    tools: ["Unity"],
    image: "/realisation/fragment/fragment.png",
    description: "Exprimer des émotions par l'environnement et guider le joueur sans interface directe.",
    contributions: [
      "Création d'un gameplay expressif",
      "Expression des émotions par l'ambiance",
      "Réflexion sur le guidage joueur"
    ]
  },
  {
    title: "Game Designer — So'Briquet",
    type: "Jeu vidéo",
    mode: "Solo",
    year: "2025",
    platform: "PC",
    engine: "Unity",
    duration: "1 Mois",
    team: "Solo",
    role: "Game Design, conception des mécaniques",
    tools: ["Unity"],
    image: "/realisation/sobriquet/sobriquet.png",
    description: "Recherche sur la manière dont le level design peut guider le joueur dans les FPS sans casser l'immersion.",
    contributions: [
      "Analyse de références FPS",
      "Étude des signes visuels et spatiaux",
      "Réflexion sur le guidage joueur",
      "Rédaction d'un mémoire complet"
    ]
  },
  {
    title: "Level Design Portal 2",
    type: "Blocking",
    mode: "Solo",
    year: "2025",
    platform: "PC",
    engine: "Hammer Editor",
    duration: "1 Mois",
    team: "Solo",
    role: "Level Design, blocking, puzzle design",
    tools: ["Unity", "Photoshop"],
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    description: "Création d'un niveau Portal 2 en partant du blocking jusqu'à l'habillage, axé sur la progression des puzzles.",
    contributions: [
      "Conception du puzzle principal",
      "Blocking et itérations",
      "Étude des signes visuels de Portal 2",
      "Habillage et finitions"
    ]
  },
  {
    title: "Level Design Far Cry 5",
    type: "Blocking",
    mode: "Solo",
    year: "2025",
    platform: "PC",
    engine: "Far Cry Arcade",
    duration: "1 Mois",
    team: "Solo",
    role: "Level Design, blocking, game feel",
    tools: ["Unity", "Photoshop"],
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    description: "Reproduction d'une zone de Far Cry 5 en blocking pour analyser les choix de level design du studio.",
    contributions: [
      "Analyse du level design original",
      "Blocking fidèle à la référence",
      "Réflexion sur l'intention du designer",
      "Documentation des apprentissages"
    ]
  },
  {
    title: "Long Night At Grandma's",
    type: "Jeu vidéo",
    mode: "Équipe",
    year: "2026",
    platform: "Mobile",
    engine: "Unity",
    duration: "1 Mois",
    team: "Équipe",
    role: "Lead Game Designer",
    tools: ["Unity"],
    image: "/realisation/longnigth/longnigth.png",
    description: "Jeu de réflexion mobile où le joueur explore la maison de sa grand-mère en résolvant des énigmes progressives.",
    contributions: [
      "Direction du game design",
      "Conception des mécaniques de puzzle",
      "Itérations et tests joueurs",
      "Documentation de game design"
    ]
  },
  {
    title: "Level Design Plague Tale",
    type: "Blocking",
    mode: "Solo",
    year: "2026",
    platform: "PC",
    engine: "Unreal Engine",
    duration: "1 Mois",
    team: "Solo",
    role: "Level Design, blocking, ambiance",
    tools: ["Unity", "Photoshop"],
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    description: "Reproduction d'une zone de A Plague Tale Requiem pour analyser la direction artistique et le level design narratif.",
    contributions: [
      "Analyse du level design de référence",
      "Blocking fidèle à la scène originale",
      "Étude de la narration environnementale",
      "Rapport d'analyse"
    ]
  },
];
